#服务端口
server:
  port: 8001

#服务名
spring:
  application:
    name: service-edu

#  环境设置：dev,test, prod
  profiles:
    active: dev
#  数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/guli_college
    password: 1234
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+11

#Mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#设置日志级别: 日志的级别如下: TRACE < DEBUG < INFO < WARN < ERROR < FATAL(信息显示由少到多)
#logging:
#  level:
#    com.atguigu: debug

